### ISSUE TITLE
Session support

### ISSUE THREAD

**Issue by EtienneBruines** [gavv/httpexpect#7] opened 2016-06-23 08:13 UTC
Hi!

First-off: awesome framework. 

Secondly, I have noticed that there's no support for session/cookie-data?

I can login using 

```go
	e.POST("/login/").WithForm(data).
		Expect().
		Status(http.StatusFound)
```

But on successive calls, the retrieved cookie is not being used. Seeing as most pages will require some kind of authentication, I would expect this feature to exist? (either now or in the future)

**Comment by gavv** [comment] 2016-06-23 10:39
Thanks for feedback.

You can already do this using non-default client with non-nil cookie jar, e.g.:

```go
import (
    "golang.org/x/net/publicsuffix"
    "net/http"
    "net/http/cookiejar"
    "testing"
)

func TestFoo(t *testing.T) {
    jar, err := cookiejar.New(&cookiejar.Options{
        PublicSuffixList: publicsuffix.List, // this is optional but recommended
    })
    if err != nil {
        panic(err)
    }
    client := &http.Client{
        Jar: jar,
    }
    e := httpexpect.WithConfig(httpexpect.Config{
        BaseURL:  "http://example.com",
        Client:   client,
        Reporter: httpexpect.NewAssertReporter(t),
    })

    ...
}
```

However, enabling cookies seems to be a common case, so I've added `httpexpect.DefaultClient()` which is used if the user didn't provide custom client.

Thus, cookies should work by default now. Could you check it?

Related: we also need cookie setter for request and cookie checker for response, I'll add them soon.

**Comment by EtienneBruines** [comment] 2016-06-23 11:12
I have read your commit, and it looks very nice & promising - thank you for that. 

As for the checking if it works: currently I'm using `httpexpect` together with `iris`, so it takes a little bit of searching where the `Jar` is defined there. (*if* it's even defined somewhere)

**Comment by gavv** [comment] 2016-06-23 11:20
Why are your looking for it in iris? AFAIK `cookiejar` is a client-side thing. See [`http.Client`](https://golang.org/pkg/net/http/#Client):

```go
        // Jar specifies the cookie jar.
        // If Jar is nil, cookies are not sent in requests and ignored
        // in responses.
        Jar CookieJar
```

httpexpect now uses non-nil jar by default, so it's probably no need to use jar outside httpexpect at all. `http.Request` and `http.Response` should automatically use the jar.

**Comment by EtienneBruines** [comment] 2016-06-23 11:22
Well, following the example code, I defined this:

```go
	handler = iris.NoListen().Handler
	client = fasthttpexpect.NewBinder(handler)
```

The client is thereby no `http.Client`, but a networkless wrapper (don't ask me why). So I'm looking into that. (btw, I'm also on https://gitter.im/kataras/iris in case you want to chat)

**Comment by gavv** [comment] 2016-06-23 11:34
I see now. Well, this is a problem, and currently there is no session support in networkless mode. I'll look what we can do.

As a workaround, you can temporary switch to network mode.

**Comment by gavv** [comment] 2016-06-23 13:29
I've added cookie jar support to networkless mode.

Unfortunately, API is not backward compatible:
* `fasthttpexpect` package was merged into `httpexpect` package to avoid circular imports
* `fasthttp` client adapter was removed (it seems to be quite useless)
* `fasthttp` handler adapter was renamed from `fasthttpexpect.Binder` to `httpexpect.FastBinder`

Finally, `httpexpect.Binder` and `httpexpect.FastBinder` now have cookie jar support, just like `http.Client`. It's enabled by default if you're using `NewBinder` and `NewFastBinder`.

So you can change:

```go
client = fasthttpexpect.NewBinder(handler)
```

to:

```go
client = httpexpect.NewFastBinder(handler)
```

and check if cookies are working now.

**Comment by gavv** [comment] 2016-06-23 13:56
Also note that default cookie jar uses `golang.org/x/net/publicsuffix` and thus ignores cookies if request url is empty.

So don't forget to pass URL to `httpexpect.New` or `httpexpect.WithConfig`.

**Comment by gavv** [comment] 2016-06-27 14:54
Cookie setter (for request) and inspector (for response) are now available too.

**Comment by gavv** [comment] 2016-06-30 09:28
`Binder` API is changed once more (but I'm preparing for stable release with frozen API).

See [this example](https://github.com/gavv/httpexpect#use-http-handler-directly):

```go
    e := httpexpect.WithConfig(httpexpect.Config{
        Reporter: httpexpect.NewAssertReporter(t),
        Client: &http.Client{
            Transport: httpexpect.NewFastBinder(handler),
            Jar:       httpexpect.NewJar(),
        },
    })
```

`Binder` implements `http.RoundTriper` (backend for client) instead of `http.Client`, so that we can reuse `http.Client` code, including cookie jar support.

**Comment by gavv** [comment] 2016-06-30 15:24
I've added [example](https://github.com/gavv/httpexpect/blob/master/example/iris_test.go#L100) that uses iris sessions and works in networkless mode.

It works, so I'm closing this issue. Feel free to reopen.

**Closed by gavv** 2016-06-30 15:24 UTC
Labels: enhancement

**Comment by EtienneBruines** [comment] 2016-06-30 21:34
@gavv Thank you for your effort; your example looks nice.

I got it to compile in my `_test.go` file, yet running into a nil-pointer exception (in the Go `net/http`). Not sure where the error is yet; will edit this message when I know more.

**Comment by gavv** [comment] 2016-06-30 21:50
@EtienneBruines.

It seems to be an issue with redirects. Could you please open a new issue with this panic?

I'll try to reproduce it, but it will be great if you can also post a minimal example that reproduces the crash.
