### ISSUE TITLE
printing body when unexpected status code

### ISSUE THREAD

**Issue by Leryan** [gavv/httpexpect#84] opened 2020-11-21 00:20 UTC
Hi 👋 

I would like to know if you would be interested in having a new `Expect().Status(x)` behavior that would print out the response body if the status is not as expected.

My motivation is that i want to write scenarios instead of unitary endpoint tests. And for that, i need to use the "Require" reporter that will stop immediately after the first error encountered, otherwise the results are completely broken after the first failure :)

I have an idea for implementation: through configuration, being able to provide a custom status formatter/checker instead of the default, current implementation. This formatter/checker would be called after the chain check and receive the response as parameter.

What do you think?

**Comment by gavv** [comment] 2020-12-21 17:54
Hi, I think this makes sense and actually we already have an issue for a very similar feature: #69. Will it solve your problem? The issue is still in progress though.

**Comment by Leryan** [comment] 2020-12-21 18:30
yep that looks absolutely great! :)

**Comment by gavv** [comment] 2020-12-21 18:32
Great, then closing this. I've added a link to this issue to #69.

**Closed by gavv** 2020-12-21 18:32 UTC
Labels: discussion
