### ISSUE TITLE
Get empty body when test static file with fasthttp

### ISSUE THREAD

**Issue by gosilent** [gavv/httpexpect#16] opened 2016-07-03 05:57 UTC
hi~

I write some simple code to check this issue.

fileserver.go
```go
import (
	"github.com/valyala/fasthttp"
)

func fileHandler() fasthttp.RequestHandler {
	fs := &fasthttp.FS{
		Root:               "./files",
		IndexNames:         []string{"index.html"},
		GenerateIndexPages: false,
		Compress:           true,
		AcceptByteRange:    true,
	}
	fsHandler := fs.NewRequestHandler()

	return func(ctx *fasthttp.RequestCtx) {
		fsHandler(ctx)
	}
}
```

fileserver_test.go
```go
import (
	"net/http"
	"testing"

	"github.com/gavv/httpexpect"
)

func fileTester(t *testing.T) *httpexpect.Expect {
	handler := fileHandler()

	return httpexpect.WithConfig(httpexpect.Config{
		Client: &http.Client{
			Transport: httpexpect.NewFastBinder(handler),
			Jar:       httpexpect.NewJar(),
		},
		Reporter: httpexpect.NewAssertReporter(t),
		Printers: []httpexpect.Printer{
			httpexpect.NewDebugPrinter(t, true),
		},
	})
}

func TestFileServe(t *testing.T) {
	tester := fileTester(t)

	tester.GET("/static.txt").Expect().Status(200).Body().Equal("static")
}
```
test report:

```
 $ go test                                                                          
--- FAIL: TestFileServe (0.01s)
	printer.go:55: GET /static.txt HTTP/1.1

	printer.go:72: HTTP/0.0 200 OK 7.199489ms
		Accept-Ranges: bytes
		Content-Type: text/plain; charset=utf-8
		Last-Modified: Sun, 03 Jul 2016 05:44:34 GMT
		Content-Length: 0

        Error Trace:    reporter.go:22
			chain.go:21
			string.go:116
			fileserver_test.go:28
	Error:
			expected string equal to:
			 "static"

			but got:
			 ""

FAIL
exit status 1
FAIL	github.com/go-gas/testfasthttp/teststatic	0.023s
```

http code 200
So the file exist, but content is empty.
But actually there have a simple string "static" in that file.

**Comment by gavv** [comment] 2016-07-03 10:45
Thanks for reporting.

Looks like a bug in fasthttp. I've sent a PR, waiting for response from them now.

**Comment by gosilent** [comment] 2016-07-03 11:31
hey, do you have the same issue?
I delete the $GOPATH/src directory, and download all package again, then I can passed the test.
I don't know what happened, maybe some packages are not the newest version.
anyway, I passed the test now.

**Comment by gavv** [comment] 2016-07-03 11:55
Great that you caught it!

The bug is no longer reproduced with fresh `valyala/bytebufferpool` (I think [this commit](https://github.com/valyala/bytebufferpool/commit/21a4b2115581cdabcc9cd97b1624d56785fc407e)). I'll update the PR.

**Comment by gavv** [comment] 2016-07-03 12:22
The bug in fasthttp no longer affects httpexpect, so closing this.

**Closed by gavv** 2016-07-03 12:22 UTC
Labels: bug
